services:
  - type: web
    name: tweets-gen
    env: node
    branch: render
    startCommand: node .output/server/index.mjs
    buildCommand: npm install && npm run build
    envVars:
    - key: NITRO_PRESET
      value: render-com
